### ISSUE TITLE
plot_map has an error：The basemap cannot be loaded correctly 

### ISSUE THREAD

**Issue by hyyyy123** [ni1o1/transbigdata#1]
![c4d26038b608cb1f7b320075c326546](https://user-images.githubusercontent.com/95064434/143526032-4ed73024-f959-4f6e-b89b-764be6f34eb2.png)

**Comment by ni1o1** [comment]
更新transbigdata版本到0.1.29，然后按这个设置一下https://transbigdata.readthedocs.io/zh_CN/latest/plot_map.html

**Comment by hyyyy123** [comment]
> 更新transbigdata版本到0.1.29，然后按这个设置一下https://transbigdata.readthedocs.io/zh_CN/latest/plot_map.html

好的，谢谢！
