### ISSUE TITLE
[JOSS] ValueError in Example 4 notebook

### ISSUE THREAD

**Issue by anitagraser** [ni1o1/transbigdata#12]
In `Example 4-pNEUMA trajectory dataset processing,ipynb`, I get the following error: 

![image](https://user-images.githubusercontent.com/590385/148657986-c36346f4-43b7-4bc4-8969-a0328aae8889.png)

xref: [openjournals/joss-reviews#4021](https://github.com/openjournals/joss-reviews/issues/4021)

**Comment by ni1o1** [comment]
I ran `Example 4-pNEUMA trajectory dataset processing.ipynb` again but I didn't encounter the above problem. This error happens when the input GeoDataFrame `tmpgdf_data` is empty, perhaps you lose the content of `tmpgdf_data` in previous steps.

**Comment by anitagraser** [comment]
It looks like there is no track_id 2138 in the provided dataset. The maximum in gdf_data is 157:

![image](https://user-images.githubusercontent.com/590385/148679271-a872b563-3cb5-463d-9d6a-463868000c27.png)

**Comment by yuanjian24** [comment]
Hi there, according to your picture, `gdf_data` only has 188 rows. However, the right data should contain 10674 rows of data. Please make sure that you got the right dataset by reading this file:
```
data = pd.read_csv('data/pNEUMA_tbd_sample.csv')
```
and run every cell before the mentioned cell.

![image](https://user-images.githubusercontent.com/50770426/148680027-016ac654-7d38-4e7c-9063-bc2238088875.png)

Or, you can also directly replace the `tmp_gdf_data` with `gdf_data`:

```
# get the nearest node of each point on the map
gdf_data = tbd.ckdnearest_point(gdf_data, nodes)

# extract the o/d node
o_index, d_index = gdf_data.iloc[0]['index'], gdf_data.iloc[-1]['index']
o_node_id, d_node_id = list(nodes[nodes['index']==o_index].index)[0], \
                       list(nodes[nodes['index']==d_index].index)[0]
print(o_node_id, d_node_id)
gdf_data.head()
```
![image](https://user-images.githubusercontent.com/50770426/148679966-ddf38bdc-e258-4512-8297-d0975500094a.png)

**Comment by anitagraser** [comment]
I just pulled the lastest version from the repo and the issue remains. 

`gdf_data` is created from `data_sparsify_clean` which only has 128 rows:

```gdf_data = gpd.GeoDataFrame(data_sparsify_clean, ```

This has to be fixed in the notebook.

**Comment by yuanjian24** [comment]
This is a little bit weird, I have double-checked the code. To solve the problem, I have made the `data_sparsify` dataframe to a CSV file: `data/data_sparsify.csv`. Please pull again and run all the cells again to see if it works. 

![image](https://user-images.githubusercontent.com/50770426/148681464-e7cc7d53-bfe6-49a7-bc83-2997ab7e80e5.png)

Use `data_sparsify` to test `tbd.ckdnearest_point` if it still doesn't work

**Comment by anitagraser** [comment]
I don't understand what's going on here. Maybe it's a local issue. @jGaboardi does it work for you?

![image](https://user-images.githubusercontent.com/590385/148682078-93b92bbf-0977-4dc8-b441-d506a7c9cbe3.png)

**Comment by anitagraser** [comment]
Rerunning the notebook over-writes your provided csv. So there should probably be a check if the file already exists.

With your file, the following cells run. 

One strange effect is that I get the following plot:
![image](https://user-images.githubusercontent.com/590385/148682218-33b6dc39-b3de-4db7-8b0c-2b21a84a111d.png)

when the checked in version shows:
![image](https://user-images.githubusercontent.com/590385/148682239-f77caeb0-935a-47eb-a338-517424109a46.png)

**Comment by yuanjian24** [comment]
Hi, I have updated the e.g. 4 notebook:   

The file `data/data_sparsify.csv` will not be overwritten now, and I added a file check and a check-points. You can start from here:
![image](https://user-images.githubusercontent.com/50770426/148684767-03c39e63-8006-4e80-b5aa-8e171fe42097.png)

Regarding the second problem, a `GeoDataFrame` format is required for visualization (with the column of 'geometry')
The code in the red box can print the list of vehicles in the sequence of points number, you can choose any number or follow my codes:
![image](https://user-images.githubusercontent.com/50770426/148684919-1a8c0d07-9b1f-4da5-9e38-8579d0680f52.png)

**Comment by jGaboardi** [comment]
@anitagraser hmmm. I did not have any issues with the original `Example 4-pNEUMA trajectory dataset processing.ipynb` and could reproduce the notebook.

**Comment by anitagraser** [comment]
Might be a local issue then. I'm testing on Win10 with Conda. 

In my projects, I find it helpful to set up the notebooks so they can be tested on MyBinder. It gives some extra assurance that the notebooks also work on other machines than my own.

**Comment by anitagraser** [comment]
Fixed in current version
