### ISSUE TITLE
[JOSS] moving pandas citation

### ISSUE THREAD

**Issue by jGaboardi** [ni1o1/transbigdata#14]
I seem to have made in mistake (618f7c8e5d5aecdc3e4dce08d0b3e6a5d3ddc366) in the MovingPandas citation that omits the journal title (see line 100 [here](https://github.com/openjournals/joss-papers/blob/joss.04021/joss.04021/10.21105.joss.04021.pdf)).

**Comment by jGaboardi** [comment]
Hmmmm. This is still an issue after 3b7e997c66cd474c797db7a0f0f4afc00a2328a8 (omission of the journal title). Maybe I'm making an obvious syntax problem?

@ni1o1 @anitagraser @martinfleis

**Comment by jGaboardi** [comment]
#19 solved the underscore problem, but now it seems that the hyphen in the journal name is rendering.

https://github.com/openjournals/joss-papers/blob/joss.04021/joss.04021/10.21105.joss.04021.pdf

**Comment by anitagraser** [comment]
xref: [openjournals/joss-reviews#4021](https://github.com/openjournals/joss-reviews/issues/4021)

**Comment by yuanjian24** [comment]
> #19 solved the underscore problem, but now it seems that the hyphen in the journal name is rendering.
> 
> https://github.com/openjournals/joss-papers/blob/joss.04021/joss.04021/10.21105.joss.04021.pdf

Hi, the hyphen in the citation is now fixed: 
![image](https://user-images.githubusercontent.com/50770426/154952774-11356b29-6054-48b7-9d2b-9bd4a27852d0.png)
@jGaboardi
