### ISSUE TITLE
tbd.data_summary中 col参数的设置问题

### ISSUE THREAD

**Issue by yuanjian24** [ni1o1/transbigdata#2]
当执行如下代码：
`tbd.data_summary(df, col=['track_id', 'time', 'lon', 'lat'], show_sample_duration=True)`
出现如下报错：
ValueError: too many values to unpack (expected 2)
![image](https://user-images.githubusercontent.com/50770426/143867204-acafa2a2-13b4-427f-b2f7-4de20fe084de.png)

这与文档描述不一致，虽然这貌似是一个小问题

另外，针对采样间隔极低的轨迹数据，其显示的也有问题，应该是小数点省略的太多了
![image](https://user-images.githubusercontent.com/50770426/143867740-e6d97816-09dc-4a8a-b998-ecd6e1a31419.png)

这貌似也是个小问题

**Comment by yuanjian24** [comment]
再补充一个小问题：设置了`show_sample_duration=True`之后，传入的数据，其时间字段一栏就会被改变。
不设置上述命令，就不会有问题
![image](https://user-images.githubusercontent.com/50770426/143869650-7159e081-c7c7-450f-a34e-76a28f2e6270.png)

**Comment by ni1o1** [comment]
文档中介绍，transbigdata.data_summary(data, col=['Vehicleid', 'Time'], show_sample_duration=False)输入的应该是只有两列，ID与时间即可，因为有些数据不一定有经纬度。
更新了0.2.2版本，对小数点问题增加了roundnum参数可以自己设定小数点位数。时间字段一栏就会被改变的问题也修复了，可以尝试一下。
