### ISSUE TITLE
[JOSS] Install instructions: recommended Python versions

### ISSUE THREAD

**Issue by anitagraser** [ni1o1/transbigdata#24]
This is a follow-up of https://github.com/ni1o1/transbigdata/issues/6. 

Please include the recommended Python version(s) in the README installation section.

xref: [openjournals/joss-reviews#4021](https://github.com/openjournals/joss-reviews/issues/4021)

**Comment by ni1o1** [comment]
Thanks, I add the recommended Python versions in the README and the docs
