### ISSUE TITLE
[JOSS] Missing dependencies after conda install

### ISSUE THREAD

**Issue by anitagraser** [ni1o1/transbigdata#25]
I followed the conda install instructions 

> You can also install TransBigData by conda-forge, this will automaticaly solve the dependency, it can be installed with:
>
> `conda install -c conda-forge transbigdata`

and it seems that not all dependencies are resolved because I get 

`ModuleNotFoundError: No module named 'scipy'`

![image](https://user-images.githubusercontent.com/590385/154849155-f1820093-9cb1-4c56-9882-201427426021.png)

xref: [openjournals/joss-reviews#4021](https://github.com/openjournals/joss-reviews/issues/4021)

**Comment by anitagraser** [comment]
In my attempt to reevaluate https://github.com/ni1o1/transbigdata/issues/12, I have, so far, run

```
conda create -n transbigdata -c conda-forge python=3.9 
conda activate transbigdata
conda install -c conda-forge transbigdata
conda install -c conda-forge jupyterlab
conda install -c conda-forge scipy
conda install -c conda-forge osmnx
```

**Comment by anitagraser** [comment]
To run the other notebooks, users also need: keplergl and seaborn

**Comment by anitagraser** [comment]
Overall, it looks like conda users should be instructed to install everything from https://github.com/ni1o1/transbigdata/blob/main/requirements.txt + osmnx

**Comment by ni1o1** [comment]
I added the `scipy` dependency into the conda recipe. The `osmnx`,`keplergl` and `seaborn` are the optional dependency that only used in the examples, I add the instructions of how to install these packages into the example ipynb.
