### ISSUE TITLE
[JOSS] ModuleNotFoundError: No module named 'plot_map' in Example 1 notebook

### ISSUE THREAD

**Issue by anitagraser** [ni1o1/transbigdata#27]
![image](https://user-images.githubusercontent.com/590385/154851849-1c37758b-ea74-4e60-bd3c-8246de9a8c7a.png)

xref: [openjournals/joss-reviews#4021](https://github.com/openjournals/joss-reviews/issues/4021)

**Comment by ni1o1** [comment]
`transbigdata` no longer depend on `plot_map`. I deleted this line of code and the problem is fixed.
