### ISSUE TITLE
[JOSS] State of the field?

### ISSUE THREAD

**Issue by jGaboardi** [ni1o1/transbigdata#4]
Currently no other similar software packages are mentioned in the manuscript, which is a requirement. There should be an overview of comparable packages, even/especially if they are not written in Python. Further, if no other packages exist this should be mentioned.

xref: [this comment](https://github.com/openjournals/joss-reviews/issues/4021#issuecomment-998864320) from @anitagraser.

**Comment by ni1o1** [comment]
The `state of the art` part introducing similar software in spatial-temporal data analysis field is added to te manuscript

**Comment by jGaboardi** [comment]
xref: #13
