### ISSUE TITLE
line, stop = tbd.getbusdata('深圳', ['2号线']) 报错：No such busline

### ISSUE THREAD

**Issue by MissChengLX** [ni1o1/transbigdata#42]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MissChengLX** [comment]
地铁站名是正确的，但是检索不到数据

**Comment by ni1o1** [comment]
> line, stop = tbd.getbusdata('深圳市', ['深圳地铁2号线'])

这个可以

**Comment by MissChengLX** [comment]
好的，感谢回复，获取到一部分，好像也不是全部的站点

**Comment by MissChengLX** [comment]
> > line, stop = tbd.getbusdata('深圳市', ['深圳地铁2号线'])
> 
> 这个可以

好的，感谢回复，获取到一部分，好像也不是全部的站点

**Comment by MissChengLX** [comment]
> > line, stop = tbd.getbusdata('深圳市', ['深圳地铁2号线'])
> 
> 这个可以

你好，在请教个问题，就是我使用 G = tbd.metro_network(stop)，构建的网络图不是根据站点作为节点的吗，为什么网络G 的节点数量与地铁站点的数量 不一致呢

**Comment by ni1o1** [comment]
一个站点如果是换乘站，则会被考虑为多个节点
