### ISSUE TITLE
[JOSS] Community Guidelines?

### ISSUE THREAD

**Issue by jGaboardi** [ni1o1/transbigdata#5]
There are currently no Community Guidelines (*Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support*). Thorough community guidelines can be added [here](https://github.com/ni1o1/transbigdata/community), and also some more description can be given in the [Related Links](https://github.com/ni1o1/transbigdata#related-links) section in `README.md`.

xref: openjournals/joss-reviews#4021

**Comment by ni1o1** [comment]
We have added the contribution guidelines, code of conduct into the repo.
