### ISSUE TITLE
OD集计可视化时遇到的问题

### ISSUE THREAD

**Issue by uncle-leeeeee** [ni1o1/transbigdata#51]
学长您好，今天我按照共享单车数据社区发现那个例子，来用货车的gps数据进行可视化时，遇到如图所示的问题，OD集计可视化效果没有达到预期，请问是什么原因造成的呢？哪个参数或哪个地方需要进行修正，谢谢您的答复！
![Uploading 1654166291383.png…]()
![1654166304040](https://user-images.githubusercontent.com/56970200/171612453-ba932c2f-886d-4aa2-977f-95f7cfe025a7.png)
![1654166249763](https://user-images.githubusercontent.com/56970200/171612384-557064ba-6153-47e0-ad69-cf07f7ce6cee.png)

**Comment by uncle-leeeeee** [comment]
![Uploading 1654166291383.png…]()
![1654166712996(1)](https://user-images.githubusercontent.com/56970200/171613393-bf496c87-3c61-4a05-be60-34964e1f2899.png)

**Comment by ni1o1** [comment]
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/53589767/171637233-881c92bc-ba08-459e-be08-0d1ac1afd95f.png">
这里改为end

**Comment by uncle-leeeeee** [comment]
> <img alt="image" width="1227" src="https://user-images.githubusercontent.com/53589767/171637233-881c92bc-ba08-459e-be08-0d1ac1afd95f.png">
> 
> 这里改为end

谢谢学长，但但我改完后感觉还是不太对，是数据本身的问题嘛？
![1654176220748](https://user-images.githubusercontent.com/56970200/171640976-e365394d-b856-4344-9a78-eff8b277f9ad.png)

**Comment by uncle-leeeeee** [comment]
> > > <img alt="image" width="1227" src="https://user-images.githubusercontent.com/53589767/171637233-881c92bc-ba08-459e-be08-0d1ac1afd95f.png">
> > > 这里改为end
> > 
> > 
> > 谢谢学长，但但我改完后感觉还是不太对，是数据本身的问题嘛？ ![1654176220748](https://user-images.githubusercontent.com/56970200/171640976-e365394d-b856-4344-9a78-eff8b277f9ad.png)
> 
> 是的
学长您之前有遇到这样的状况吗？我有点不太理解为什么会这样子....数据起终点我自己在图上标过，但看不出来有什么问题，这个OD集计要画出比较好的效果是有什么要求吗？
![全省](https://user-images.githubusercontent.com/56970200/171647655-db224aae-f661-4d31-abcf-3c41f9eee8d8.png)

**Comment by ni1o1** [comment]
建议缩小显示范围，栅格调大，隐藏小的OD

**Comment by uncle-leeeeee** [comment]
> 建议缩小显示范围，栅格调大，隐藏小的OD

我试一试，谢谢学长，向您学习，tql！
