### ISSUE TITLE
FileNotFindError in plotmap.py

### ISSUE THREAD

**Issue by liq77** [ni1o1/transbigdata#55]
There were some problems when I was trying to set imgsavepath, it seems like “filepath = searchfile('mapboxtoken.txt')” in line 68 doesn't work. when I typing the following code in my jupyternotebook.
> import transbigdata as tbd
> tbd.set_imgsavepath(r'/home/liqi/CodeSpace/Map_tile/')

I don't know if it was caused by miniconda virtual environment or something else.

**Screenshots**
![image](https://user-images.githubusercontent.com/67859191/178694496-2062c021-d826-41fe-8492-9038fc81462a.png)

 - OS: Ubuntu20.04LTS

**Comment by ni1o1** [comment]
Can you update to `transbigdata` version 0.4.11 and try again, this issue should be resovled. 
0.4.11 change the way to store the mapbox settings. `mapboxtoken` and `imgsavepath` are now store at `config.ini` in transbigdata source code folder.

**Comment by liq77** [comment]
thanks a lot
