### ISSUE TITLE
[JOSS] Installation & Dependencies

### ISSUE THREAD

**Issue by jGaboardi** [ni1o1/transbigdata#6]
In order to make it most clear for users to install `geopandas`, the link in [`README`](https://github.com/ni1o1/transbigdata#installation) and the install docs should be: https://geopandas.org/en/stable/getting_started.html#installation

Also, the following packages are used in the docs/tutorials and should be added to [dependencies](https://transbigdata.readthedocs.io/en/latest/getting_started.html#id3) list:
  * `CoordinatesConverter>=0.1.4`
  * `leuvenmapmatching`
  * `igraph` (optional)
  * `osmnx` (optional)
  * `plot_map`
  * `rtree`
  * `seaborn` (optional)
  * `shapely`

xref: openjournals/joss-reviews#4021

**Comment by anitagraser** [comment]
It would also be helpful to recommend a Python version. 

I see that https://github.com/ni1o1/transbigdata/runs/4740487080?check_suite_focus=true sets up 3.6 but 3.6 support is deprecated by GeoPandas (https://github.com/geopandas/geopandas/commit/8c1e3531b8ed23e086ca2a3eede81e344a591a5d)

**Comment by anitagraser** [comment]
I had to explicitly conda install python-igraph to make `import igraph` work.

**Comment by jGaboardi** [comment]
@anitagraser `conda install igraph` did not work for me (due to what you mentioned above), but `pip install igraph` did work correctly.

**Comment by jGaboardi** [comment]
@ni1o1, as Anita points out above, Python 3.6 is deprecated by GeoPandas (and much of the scientific Python community). I would suggest testing in *at least* Python 3.7. However, is there a reason to not test in Python 3.9 or even 3.10?

**Comment by ni1o1** [comment]
> @ni1o1, as Anita points out above, Python 3.6 is deprecated by GeoPandas (and much of the scientific Python community). I would suggest testing in _at least_ Python 3.7. However, is there a reason to not test in Python 3.9 or even 3.10?

I tried to setup the testing in Python3.10 but it failed to install the `fiona` dependency. The testing is now setup in Python3.9 and passed.

**Comment by jGaboardi** [comment]
OK, I'm can put in PR that will test on matrix of Python 3.{7,8,9}, if you like. Let me know.

Another consideration moving forward (though not necessary for the JOSS paper review) is to provide an install via `conda-forge`. This will clear up a lot of install/dependency issues and make `transbigdata` more accessible for users.

**Comment by ni1o1** [comment]
> OK, I'm can put in PR that will test on matrix of Python 3.{7,8,9}, if you like. Let me know.
> 
> Another consideration moving forward (though not necessary for the JOSS paper review) is to provide an install via `conda-forge`. This will clear up a lot of install/dependency issues and make `transbigdata` more accessible for users.

OK! Thanks a lot!
I will look into the conda-forge install at once.
