### ISSUE TITLE
计算过程中，数据发生变化

### ISSUE THREAD

**Issue by fanqiangniubi** [ni1o1/transbigdata#65]
大家好，我在用transBigData 聚合集计栅格内数据量 的时候发现，先前都在0~1的数据，计算之后都自动变成1了，怎么在计算过程中保持数据不变呢？
![L%1IZ(@1W1U@F8AT17@`VG3](https://user-images.githubusercontent.com/87556341/201522135-571a8c78-4be9-4093-8572-e31f2d138337.png)

**Comment by ni1o1** [comment]
> 大家好，我在用transBigData 聚合集计栅格内数据量 的时候发现，先前都在0~1的数据，计算之后都自动变成1了，怎么在计算过程中保持数据不变呢？ ![L%1IZ(@1W1U@F8AT17@`VG3](https://user-images.githubusercontent.com/87556341/201522135-571a8c78-4be9-4093-8572-e31f2d138337.png)

在你画蓝线的那一行代码，是pandas的groupby分组聚合的操作。你必须指定聚合操作什么类型，如果用count就是分组计数，如果用mean就是分组取平均值，出来的值取决于你想要做什么样的聚合操作，详情可以参考：https://blog.csdn.net/qq_27575895/article/details/86768918
