### ISSUE TITLE
构建地铁网络拓扑时遇到的问题

### ISSUE THREAD

**Issue by gggaiii** [ni1o1/transbigdata#72]
学长好！在构建地铁网络拓扑时，使用tbd.metro_network()函数时报错'DataFrame' object has no attribute 'append'，是代码里面的edge = edge1.append(edge2)这一行，然后在网上查了一下说是pandas版本更新后舍弃了append方法，现在使用concat方法好像。我把代码改成edge = pd.concat([edge1, edge2])后就可以正常运行了，不知道学长要不要看看更新一下代码之类的~
学长的教程和Transbigdata库真的给了我很大的帮助，也在这里谢谢学长啦~

**Comment by ni1o1** [comment]
更新0.5.0版本已修复
