### ISSUE TITLE
出现报错：cannot import name 'TopologicalError' from 'shapely.geos'

### ISSUE THREAD

**Issue by Dennissy23** [ni1o1/transbigdata#79]
import时出现报错：cannot import name 'TopologicalError' from 'shapely.geos' (D:\Anaconda\envs\TransBigData\lib\site-packages\shapely\geos.py)
这是为什么呢，是我的shapely版本没安装对吗，但是我都是让conda自动安装的呀

**Comment by hanwanbing** [comment]
我也出现了这个问题，应该是shapely版本过高了（原来是2.0.1），降到版本conda install shapely=1.8.4，就可以使用了
