### ISSUE TITLE
[JOSS] target audience?

### ISSUE THREAD

**Issue by jGaboardi** [ni1o1/transbigdata#8]
Regarding the **Statement of Need**, the docs and manuscript clearly state *what* problems are being solved, but there is no mentioned of *who* the target audience is.

This should be added to:
  * the actual manuscript
  * `README.md`
  * the docs site

For reference:
* **Documentation**
  *Do the authors clearly state what problems the software is designed to solve and who the target audience is?*
* **Software paper**
  *Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?*

xref: openjournals/joss-reviews#4021

**Comment by ni1o1** [comment]
We add the statement of target audience in the `state of need` part of the manuscript, the `README.md` and the docs site.

**Comment by jGaboardi** [comment]
xref: #13
