### ISSUE TITLE
array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

### ISSUE THREAD

**Issue by GREED0408** [ni1o1/transbigdata#80]
home = tbd.mobile_identify_home(stay, col=['user_id','stime', 'etime','LONCOL', 'LATCOL','lon','lat'], start_hour=0, end_hour=24 )
home

会出现报错，说数组过于巨大 800w次停留

**Comment by ni1o1** [comment]
可以试试看拆分数据集后再尝试识别
