### ISSUE TITLE
pyproj报错信息显示，是包的版本问题吗？感谢！

### ISSUE THREAD

**Issue by xiaosanmeng** [ni1o1/transbigdata#82]
File "pyproj/_crs.pyx", line 2338, in pyproj._crs._CRS.__init__
    PJ_TYPE_VERTICAL_CRS: "Vertical CRS",
pyproj.exceptions.CRSError: Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name)

**Comment by ni1o1** [comment]
建议重新安装pyproj，确保有可用的geopandas包，再使用transbigdata
