### ISSUE TITLE
module 'transbigdata' has no attribute 'clean_same'

### ISSUE THREAD

**Issue by a28927** [ni1o1/transbigdata#87]
学长好，请问这个方法在新版本已经删除了吗，我在日志中没有找到关于它的说明。它是在您的教材《交通时空大数据分析、挖掘与可视化》的P269有被用到，谢谢！

**Comment by ni1o1** [comment]
在最新版本中已经更改为`tbd.traj_clean_redundant`

**Comment by a28927** [comment]
谢谢学长！
